[package]
name = "carpo"
version = "0.1.0"
authors = ["Larry Hsiao <larryhsiao@larryhsiao.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
confy = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
rusqlite = "0.20.0"
dirs = "2.0"
tempfile = "3"

[profile.release]
panic = 'abort'